set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr) 

# Arduino SDK base path
set(ARDUINO_SDK_PATH "/Users/kravserg/Library/Arduino15")

set(ARDUINO_TOOLCHAIN_DIR "${ARDUINO_SDK_PATH}/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-")

set(CMAKE_CXX_COMPILER ${ARDUINO_TOOLCHAIN_DIR}g++ CACHE FILEPATH "Arduino C++ compiler")
set(CMAKE_C_COMPILER ${ARDUINO_TOOLCHAIN_DIR}gcc CACHE FILEPATH "Arduino C compiler")
set(CMAKE_LINKER ${ARDUINO_TOOLCHAIN_DIR}ld CACHE FILEPATH "Arduino linker")
set(CMAKE_AR ${ARDUINO_TOOLCHAIN_DIR}gcc-ar CACHE FILEPATH "Arduino archiver")
set(CMAKE_RANLIB ${ARDUINO_TOOLCHAIN_DIR}gcc-ranlib CACHE FILEPATH "Arduino ranlib")

#SET(CMAKE_C_FLAGS   "-U__GNUC__ -U__GNUC_MINOR__" CACHE STRING "" FORCE)
#SET(CMAKE_CXX_FLAGS "-U__GNUC__ -U__GNUC_MINOR__" CACHE STRING "" FORCE)
SET(CMAKE_C_FLAGS   "-U__GNUC_MINOR__" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS "-U__GNUC_MINOR__" CACHE STRING "" FORCE)

set(CMAKE_C_STANDARD_COMPUTED_DEFAULT 11)
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT 17)

set(CMAKE_CXX17_COMPILE_FEATURES "")
set(CMAKE_CXX20_COMPILE_FEATURES "")

set(CMAKE_CXX17_STANDARD_COMPILE_OPTION "-std=c++17")
set(CMAKE_CXX17_EXTENSION_COMPILE_OPTION "-std=gnu++17")

